# Generated by Django 4.2.21 on 2025-05-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(default="null", max_length=254),
        ),
    ]
