# Generated by Django 4.2.21 on 2025-05-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipe_name", models.CharField(max_length=100)),
                ("receipe_descriptions", models.TextField()),
                ("receipe_image", models.ImageField(upload_to="receipe")),
            ],
        ),
    ]
